### PR TITLE
Allow resolve params to be injected into controllerProvider

### LINKED ISSUE #1131: controllerProvider not $injecting resolve:{} parameters
I understand that the templateProvider has a similar issue, here's the test case:

    $stateProvider.state({
        url: "/",
        controllerProvider: function(resolveParam){},
        resolve: {resolveParam: function(){ return true;}}
    });

   Unknown provider: routeParamProvider <- routeParam

### PR DESCRIPTION
**Pull request by tjwallace**
Fixes #1131

### CODE REVIEW

**Comment by christopherthielen** [comment]
Can it be that easy?

**Comment by tjwallace** [comment]
@christopherthielen I guess so...  ¯\_(ツ)_/¯

**Comment by nateabele** [comment]
Hah, looks good. Please amend the commit message to follow the contributor guidelines so that this change works correctly with our build system. Other than that, I am :+1: for merging. Thanks for your work.

**Comment by tjwallace** [comment]
@nateabele done in 42e6bf2e811a0969888da9d441c821a8ae6c8118 - wasn't exactly sure what the scope was for the commit message so I used state based off the file name. Let me know if it can be more specific and I will update.

**Comment by nateabele** [comment]
Weird, I was gonna amend it to `feat($state)` & merge it for you, but I can't even figure out how to access that commit hash. GitHub says it's in angular-ui/ui-router, but it won't let me fetch/checkou.

**Comment by tjwallace** [comment]
@nateabele I did another force push and this time it is showing up properly in the PR - https://github.com/zozi/ui-router/commit/b380c223fe12e2fde7582c0d6b1ed7b15a23579b

**Comment by nateabele** [comment]
Nice, thanks.

**Pull request merged**
