### PR TITLE
fix(angular-ui-router.d.ts): Delete angular-ui-router.d.ts

### PR DESCRIPTION
**Pull request by kenhowardpdx**
This file is out of date and breaks the build process. Deleting to defer to the community supported DefinitelyTyped version - https://github.com/borisyankov/DefinitelyTyped/issues/4035

### CODE REVIEW

**Comment by pocesar** [comment]
the one at DefinitelyTyped is actively maintained

**Comment by nateabele** [comment]
@christopherthielen @wesleycho Is this still relevant in the context of new things?

**Comment by christopherthielen** [comment]
I think we'll be generating our own .d.ts file

**Comment by nateabele** [comment]
Okay, so we're basically dropping this one anyway. Then I guess we can merge this, but the formatting issues need to be fixed: http://prjs.radify.io/#/angular-ui/ui-router/pulls/1990

**Comment by kenhowardpdx** [comment]
@nateabele I've fixed the title but it's still failing the format check. What do I need to do to get this merged?

**Comment by wesleycho** [comment]
The commit format is off - this could be an easy thing to fix by us, although generally contributions should conform to the guidelines, as mentioned [here](https://github.com/angular-ui/ui-router/blob/master/CONTRIBUTING.md#contribute).

**Comment by kenhowardpdx** [comment]
@wesleycho Thanks. I'll look at the guidelines and re-submit a PR.

**Comment by wesleycho** [comment]
No need, already merged it in :)

**Comment by kenhowardpdx** [comment]
Oh. Ok. :+1:

**Pull request closed without merging**
