### PR TITLE
Fix incorrect name of transitionsProvider on readme

### PR DESCRIPTION
**Pull request by charandas**
Its currently `transitionProvider` in the readme which is not what it is actually :smile:

### CODE REVIEW

**Comment by christopherthielen** [comment]
@charandas are you playing with feature-1.0 codebase?  How are you finding it?

**Comment by charandas** [comment]
@christopherthielen Thanks for checking in. Yes, I am interested in updating to it.

At first glance, couldn't have play well with ui-router-extras. There was some issue with a decorator call in the library.

Trying to see if my app can instead run initialization code in transition hooks.

**Comment by charandas** [comment]
Excited about what you guys are targeting for near future, for Angular 2 especially.

**Comment by christopherthielen** [comment]
@charandas ui-router-extras sticky states is not ready for the 1.0 branch.  
future states likely works.  
DSR and previous states likely do NOT work (without enabling the now-deprecated-state-events in the 1.0 $stateEventsProvider)

**Comment by charandas** [comment]
Yeah, cannot expect you to be on top of that project alongside the gargantuan duties that come with being a ui-router maintainer :grinning: 

I am interested in using the dynamic params (aka $location.search()) without a state reload with 1.0 preview. I read somewhere there is a decorator for that. Care to enlighten, please?

**Comment by christopherthielen** [comment]
Params in general (and dynamic params) are one of the chores on my list to address before the 1.0-beta.    We currently have three concepts internally managing params (ParamSet, StateParams, ParamValues) and I need to consolidate them down to two, or perhaps even one class.  As of right now, dynamic params *might* work if you use $state.params global mutable state object.  

However, we're moving people *away* from using global mutable state.  I want people to watch dynamic params using the $stateParams object injected into a hook or controller, but dynamic params aren't currently implemented there.

**Comment by charandas** [comment]
Thanks for the update. Will stay tuned. :+1:  @christopherthielen

**Pull request merged**
