### PR TITLE
add view name to $viewContentLoaded arguments

### PR DESCRIPTION
**Pull request by tamtakoe**
$viewContentLoaded is cool event, but it will be better and useful if we can get view name within handler

### CODE REVIEW

**Comment by vladgurovich** [comment]
It looks like the reason this PR is ignored is because it has no test coverage

**Comment by nateabele** [comment]
No test coverage, needs to be rebased against master, needs to follow contributor guidelines.

**Comment by eddiemonge** [comment]
@tamtakoe ^^

**Comment by nateabele** [comment]
Fixed in #2003.

**Pull request closed without merging**
