### PR TITLE
feat($state): add prependBasePath option

### PR DESCRIPTION
**Pull request by williamboman**
Also s/appendBasePath/prependBasePath/g

So, I want to generate a non-absolute href without the base path prepended and couldn't find a way of doing that.

### CODE REVIEW

**Comment by williamboman** [comment]
Status on this?

**Comment by nateabele** [comment]
Hi, sorry for not responding earlier. I don't really understand the use case for this, and I don't see how it helps you do anything that you couldn't do by generating the HREF and concatenating `$("base").attr("href")` yourself.

**Comment by williamboman** [comment]
@nateabele The default behaviour now is to concatenate the base path, with no option to turn it off. So in order to remove the base href, you'd have to do something like

```js
let href = $state.href(nextStateName, nextParams).replace(new RegExp(`^ + ${$('base').attr('href')}`));
```

to remove the base path.

So this patch makes it possible to opt-out of that behaviour (rather than opt-in - which is default).

**Comment by nateabele** [comment]
Or better yet...

```javascript
let href = $state.href(nextStateName, nextParams).substr($('base').attr('href').length);
```

Again, though, what's the use case?

**Comment by williamboman** [comment]
@nateabele Something like [this](http://plnkr.co/edit/7fbYOhgaytpDRjOfE6UV?p=preview).

**Comment by nateabele** [comment]
Okay, that makes sense. However, I'm still pretty firmly against an option flag for every one-off use case that comes up, especially when they save very little code. People propose these constantly and it would quickly get out of hand. Sorry.

I am willing to consider exposing a simple API that would allow mapping a URL to a state + parameters, which would be a useful alternative in your case, in addition to being generally useful for many developers.

**Comment by williamboman** [comment]
How about not prepending the base path if the href is not absolute? i.e.

```js
if (options.absolute) {
    url = prependBasePath(...);
}
```
It's essentially what this patch does, but in a BC manner. The native `$location` service omits the base path for relative paths.

**Comment by nateabele** [comment]
I suppose because that would break Cmd/Ctrl-clicking or copying the URL?

**Comment by williamboman** [comment]
Should it though? Browsers should take care of prepending any base path to relative links, e.g. `<a href>`, `<script src>`. I don't see why a non-absolute `$state.href()` should prepend the base path.

**Pull request closed without merging**
