### PR TITLE
feat($state): support URLs with #fragments in html5Mode

### PR DESCRIPTION
**Pull request by mismith**
Allow setting the `#` param to update the location fragment; e.g.: `ui-sref="page({name: 'name', '#': 'frag'})"` or `$state.go('page', {name: 'name', '#': 'frag'})`

This is hoping to solve the various issues found in: #701, #1187, and #1455

### CODE REVIEW

**Comment by nateabele** [comment]
Looks pretty good, thanks for putting this together. Just to be clear, what's the behavior in non-HTML5-mode? Do you just not get a fragment?

**Comment by mismith** [comment]
I would assume so, I haven't really thought that through. What would be best? Do browsers even let you set a URL like `#!/hello/world#frag`

**Comment by nateabele** [comment]
Yeah, you can put whatever you want in the URL. I believe the `$location` service takes care of parsing for you. See here: https://docs.angularjs.org/api/ng/service/$location#hash

If you can amend the commit with a test that verifies that this change mimics the above behavior (you might have to break off the `'#'` and pass it to `$location.hash()` after the call to `$location.url()`), then I'll merge this. Thanks a lot for your work on this.

**Comment by mismith** [comment]
So which would you prefer, that I enable this behaviour for non-html5Mode as well, or test that it has no effect when in that mode?

**Comment by nateabele** [comment]
I think the effect should be the same as using `$location.hash()`, so, you get an extra `#` in the URL, that the `$location` service parses out transparently. Does that make sense?

**Comment by nateabele** [comment]
Again, I _think_ you could probably just Make It Work™ by passing the `params['#']` to `$location.hash()` instead of appending it to `url`.

**Comment by mismith** [comment]
I think the issue with that would be the order of operations? If I used `.hash()` in place of appending the the url, it would fire right away, no? (rather than after the state changes)

**Comment by nateabele** [comment]
Not sure, I just assumed it would work. Anyway, if the tests pass in the new PR in both modes, good enough for me.

**Pull request closed without merging**
