### PR TITLE
fix(UrlMatcher) isOptional

### PR DESCRIPTION
**Pull request by swisstofu**
fix for isOptional is always true #2483 and unit test

### CODE REVIEW

**Comment by nateabele** [comment]
Thanks for doing this patch, but please don't modify versioning or release files. Those are for the release process only. Also, the formatting on the test looks a bit off.

**Comment by swisstofu** [comment]
sure sorry for that. everything should be fixed now.

**Comment by christopherthielen** [comment]
Thanks for the PR.  

I don't think the conditional `value !== ""` is the right change.  
It seems like it would break default value of "" (which is very common; it's the default in 0.2.x)

I'm also surprised we didn't have a unit test for a default value of ""! 

```
url: '/foo/:str',
params: {
  str: { value: "" }
}
```
or to use an example with a regexp, which 

```
url: '/foo/{param:(?:foo|bar|)}',
params: {
  param: { value: "" }
}
```

**Comment by swisstofu** [comment]
well i think then we can just get rid of the line

```javascript
if (type.name === "string" && !arrayMode && location === "path" && config.value === undefined)		
  config.value = ""
```
i've added some tests you suggested as well as mine and none are failing

**Comment by christopherthielen** [comment]
http://prjs.radify.io/#/angular-ui/ui-router/pulls/2492

Can you squash your commits and revert the changes to the `release/*` files?

**Comment by swisstofu** [comment]
done

**Comment by christopherthielen** [comment]
I merged the tests into 1.0 (`master`); the deleted code from the PR was already deleted in the 1.0 codebase.

**Pull request merged**
