### PR TITLE
docs(sample): Update to angular 1.4.1

### PR DESCRIPTION
**Pull request by blowsie**

### CODE REVIEW

**Comment by svemir** [comment]
Why 1.4.1? Is something broken in 1.4.4?

**Comment by blowsie** [comment]
1.4.1 was the latest in this project

**Comment by eddiemonge** [comment]
That folder isnt in the lib folder. 1.2.14 is there specifically.

**Comment by blowsie** [comment]
@eddiemonge what do you mean?

I simply changed a broken reference to a working one, why have you closed?

**Comment by blowsie** [comment]
image

**Comment by blowsie** [comment]
@eddiemonge Maybe you are looking at the wrong branch, please review.

**Comment by eddiemonge** [comment]
Oh I was looking at the wrong branch. My bad.

**Comment by christopherthielen** [comment]
Closing, because the ui-router sample should not belong in this branch.  We will be splitting it off into its own repository.  The work in progress is currently at https://github.com/christopherthielen/new-state-vis/

**Comment by christopherthielen** [comment]
Thanks for the PR though, blowsie!

**Pull request closed without merging**
