### PR TITLE
feat(urlMatcher): add raw encoding flag to Type

### LINKED ISSUE #1119: url encode stateparams
If i pass a string like `/default` to `$stateParams`, it seems to mess up the routing:

    var name = "/default";
    this.$state.go("app.transactions.detail", { txnName: name });

While the controller is invoked, the url is unable to switch to.
when i encode the value before passing it to $stateparams, it works.

however, ui-router should take care of doing the encoding/decoding for me.

### PR DESCRIPTION
**Pull request by nateabele**
Closes #1119

### CODE REVIEW

**Comment by christopherthielen** [comment]
very nice.

**Comment by mismith** [comment]
awesome work, thanks!

**Comment by plong0** [comment]
will this be applied to the 0.2.* release branch too?  I just added support for a raw flag to type in my local 0.2.15. Should I make a PR for that?

**Comment by nateabele** [comment]
Not sure yet. We're focused pretty heavily on getting 1.0 out the door, and since 1.0 is mostly feature-compatible with 0.2.x, getting everyone to upgrade.

**Pull request merged**
