### PR TITLE
fix(urlMatcherFactory): Slashes are now properly decoded in url params

### PR DESCRIPTION
**Pull request by ckniffen**
Fixes: #1973, #1645

### CODE REVIEW

**Comment by piotrd** [comment]
:+1: tested with a large app, works great. Can anyone merge it, please?

**Comment by ckniffen** [comment]
@piotrd have you checked #2071? I think it is a better implementation.

**Comment by piotrd** [comment]
@ckniffen: you're right. Thanks for pointing this one out, I somehow didn't notice that PR. I tested it now and unfortunately it fails for `val` being null. I made a comment in the PR about it, along with proposed improvement (https://github.com/angular-ui/ui-router/pull/2071/files#r33758421).

**Comment by ckniffen** [comment]
Closing in favor of #2071.

@piotrd I get that too.  I could not find a way around it though.

**Pull request closed without merging**
