### PR TITLE
fix(stateDirective): using on to attach an event handler instead of bind

### LINKED ISSUE #3035: element.bind is not a function with jquery.slim version
The ```.bind()``` method has been deprecaten in [version 3.0+](http://api.jquery.com/bind/).

But in the **slim build** of jQuery the method has been removed directly. So, the uiSref directive fails when tries to attach a handler to the click event.

Plunker with the error in the console: https://plnkr.co/edit/2dceELuWmG2wq3027gwD

This only occurs with the slim build. This is not failing with jqLite or jQuery full build.

Can we add support to the slim build? jqLite also supports the ```.on()```` method. We just need to replace the bind with the on and this issue is resolved.

### PR DESCRIPTION
**Pull request by navarroaxel**
fix #3035

### CODE REVIEW

**Comment by nateabele** [comment]
This is a BC-break. We can add support for `on` and `off`, but not by dropping support for `bind`/`unbind`.

**Comment by navarroaxel** [comment]
Yeah, I can see it's a breaker... How do you like the IF?
````javascript
element.bind ? element.bind("click", hookFn) : element.on("click", hookFn);
````
or this:
````javascript
element.[element.bind ? 'bind' : 'on']("click", hookFn);
````
Should I try to use ```on``` before ```bind``` or viceversa?

**Comment by christopherthielen** [comment]
I think I merged a similar commit into master

**Comment by christopherthielen** [comment]
@navarroaxel we would want to try `on` before `bind`

**Comment by navarroaxel** [comment]
Hey @christopherthielen, are you saying this commit is useless because it was covered by another one?

**Comment by navarroaxel** [comment]
Hey @nateabele, I have change the code to be keep the BC.

**Comment by christopherthielen** [comment]
I think I merged a similar commit on `master`, not `legacy`

**Comment by christopherthielen** [comment]
Thanks!

**Comment by nateabele** [comment]
Yup, thanks @navarroaxel.

**Pull request merged**
