### PR TITLE
remove extra single quote in error message

### PR DESCRIPTION
**Pull request by lookfirst**

### CODE REVIEW

**Comment by nateabele** [comment]
Thanks for the patch. Please see the contributor guidelines on correct commit message formatting.

**Comment by lookfirst** [comment]
HAAHAHAHAHAHAHAHAHAHAHAHAHAHA. If you're going to respond with a message like that for a single character fix, I'm just going to close this. Now I know to never submit another PR to this project ever again.

**Comment by leoromanovsky** [comment]
@lookfirst Before submitting a pull request, please first create a "Plunkr" to demonstrate the alleged problem.

**Comment by nateabele** [comment]
@lookfirst Hey, if you wanna blame me for not reading the contributor guidelines before wasting both of our time, that's on you.

We have build tools that operate on specific commit message formatting. What do you think we are, animals?

@leoromanovsky You know, the depth of laziness of the JavaScript community never ceases to astound me. Never has it been so easy to help the people trying to fix your problem in their abundant free time. You literally have the ability to reproduce your issue directly in front of the faces of the people trying to fix it, yet people just don't. Anyway, let me know once you have some experience running a moderately popular Open Source project, and then we'll talk.

**Comment by lookfirst** [comment]
@nateabele Of course I didn't read your contributor guidelines and it has nothing to do with being lazy. I saw the issue due to a bug in my code, came to github not even thinking about reading anything, only wanting to fix the error message. I did a quick search to find the problem in the code, I clicked the pencil on the file, edited that **single character** and submitted a PR. All in a few clicks, thanks github!

If your automated system for generating the changelog is so anal retentive that you require people to specially format their messages, **you're doing it wrong**. Don't put inane barriers up for people who are willing to contribute their time to helping you out. No matter how small the contribution is.

An example of another project doing it right... https://github.com/almost/react-native-sqlite/pull/2

**Comment by nateabele** [comment]
> Of course I didn't read your contributor guidelines and it has nothing to do with being lazy.

Wasn't referring to you.

> If your automated system for generating the changelog is so anal retentive that you require people to specially format their messages, you're doing it wrong.

Maybe. We just use the same tooling as Angular core, so you can take it up with them. It's been working out fine for us so far. Sorry your feelings were hurt.

**Pull request closed without merging**
