### PR TITLE
ui-sref-active support a class match a group state

### PR DESCRIPTION
**Pull request by liuchungui**
support like this:

`
<li><a ui-sref="data.salesman" ui-sref-active="{'text-primary': ['data.salesman.*', 'data.salesmanInfo.*']}">sales</a></li>
`

### CODE REVIEW

**Comment by christopherthielen** [comment]
Thanks for the PR!

I need a few things before I can merge this:
- CI is broken (it looks like `isArray` needs to be imported)
- We need a unit test for this (matching multiple globs)
- The documentation needs to be updated
- The commit message should start with `feat(ng1.uiSref): ` so it gets picked up in the Changelog

**Comment by liuchungui** [comment]
I use this way in my app, but it's not good, like this

`
 <li><a ui-sref="data.salesman" ui-sref-active="{'text-primary': ['data.salesman.*', 'data.salesmanInfo.*, 'data.salesmanOne.*',  'data.salesmanTwo.*',  'data.salesmanFour.*']}">sales</a></li> 
`
Have a good method to use more convenient ? 
eg.
`
<li><a ui-sref="data.salesman" ui-sref-active="{'text-primary': data.salesman**">sales</a></li> 
`

**Comment by Pirfox** [comment]
@liuchungui will you continue this PR?
If not does @christopherthielen have the time to work on it?

**Comment by christopherthielen** [comment]
@Pirfox I do not have time to work on this right now, sorry.

**Pull request closed without merging**
