### PR TITLE
Adds a code of conduct.

### PR DESCRIPTION
**Pull request by CoralineAda**

### CODE REVIEW

**Comment by jessicard** [comment]
:+1:

**Comment by btford** [comment]
:+1: – and ping @nateabele @petebacondarwin and @PascalPrecht who belong to this org and I happen to know.

"Angular UI" can use the official Angular Organization's as a starting point: https://github.com/angular/code-of-conduct

Let me know if I can help at all. This is important stuff.

**Comment by derekr** [comment]
:+1:

**Comment by doeg** [comment]
Thanks, @CoralineAda!

**Comment by nateabele** [comment]
Hey, thanks. This is a super important issue, unfortunately I'm in the middle of a family crisis this week, so I can't give it the attention it deserves right now.

In the meantime, I'd be interested to hear feedback from the community. For a lot of people this is a no-brainer, but I've heard it can also be kinda contentious...

What say you, UI Router community?

**Comment by petebacondarwin** [comment]
I don't believe there is anything contentious about clarifying how to behave in an appropriate manner when interacting with a project.

**Comment by eddiemonge** [comment]
@btford :( no mention for me

**Comment by eddiemonge** [comment]
First, thank you @CoralineAda for putting in the effort for this. We want more people helping.

I'm not going to lie, this is a boring CoC that I don't think most people will read. Even I had trouble getting through it (kind of skimmed some of it). I'm not saying this to be disrespectable. I wish there was a fun code of conduct that people would actually want to read. Most are so dry and boring that I don't think most people read them, at least not all of it anyway. I know its a serious topic and I'm not trying to make light of it in anyway. But I'd rather have people have a good laugh or smile when reading it as long as they are reading it and taking it to heart and practice.

It makes me sad that we actually have to have things like this. Sometimes it really is culture though and people just don't know better. Other times they forget there are actual people on the other end of the keyboard. I always try to imagine what would happen if I said the things I put online in person. If I would get punched in the face then its probably not the best thing to say.

I guess I'm saying I am mixed on this. It is good for the people who will read it but the people who it is intended for probably won't care anyway. I am ok with adding it or adding a different one or just adding a note to the readme or somewhere else that says something like "Treat people like they are standing in front of you and can punch you in the face if you get out of line". Grossly oversimplified and doesn't cover all cases but thats the point: nothing ever will. But I suppose something is better than nothing.

p.s. :( to no trolling: https://github.com/angular-ui/ui-router/pull/2309/files#diff-a1ee87dafebc22cbd96979f1b2b7e837R11

/rant

**Comment by doeg** [comment]
@petebacondarwin well said. :)

**Comment by nateabele** [comment]
Alright. I had a chance to sleep on this for a couple of nights, sort out my own thoughts, and consult some trusted friends who I admire for their leadership positions in open, positive, inclusive communities that I've observed or been a part of. I've also heard privately from community members who were understandably reluctant to air their views in public.

First of all, thanks for kicking off this discussion, and thanks for addressing the inappropriate comment that led to it. If nothing else, I'm proud of the fact that it was the first instance of inappropriate behavior that I've observed in 2½ years of being a maintainer on this project, and that it was resolved quickly and smoothly once raised. Hopefully the conclusion of this will be that the whole community is clear on the boundaries, and if any future inappropriate comments do occur, they won't sit unaddressed for months. :smile:

This discussion has forced me to sit and think about the type of community and culture that I want to create, the intentionality of which is something that's clearly overdue for a project at this level of visibility, but we'll get to that in a minute.

I have to say I'm a bit taken aback by the fact that the people primarily championing this have, so far as I can tell, had no prior involvement in the project. I'm not entirely sure what to make of it, but I will proceed on the assumption that you're all here in good faith.

To address the proposed CoC itself... after having read it carefully a number of times, I can't say I'm comfortable with the language. In particular, I'm uncomfortable with being made to be responsible for things outside of my purview, and I'm uncomfortable with the idea of having to mediate things that I can't observe or verify. Overall, it seems to be phrased primarily in the negative. I also carefully read [the FAQ](http://www.ashedryden.com/blog/codes-of-conduct-101-faq). I really don't love the [patronizing generalizations](http://www.ashedryden.com/blog/codes-of-conduct-101-faq#cocfaqnegative) it makes about its intended audience. I also read the CoC linked by @btford. While it's definitely phrased in a more positive way, I think we can do better.

I sat and thought about what a CoC for this project would look like, and came up with the following wish list:

 - Focus primarily on how to treat people, instead of on how _not_ to treat people
 - Address any unprofessional, discourteous, or dishonoring comments, or any other comments that take focus away from the work
 - Address sarcasm and passive-aggression
 - Be expressly apolitical; this includes any and all mention of arbitrary group identifiers
 - Create a space to collaborate and get work done; political discussions or causes are expressly forbidden
 - In the presence of ambiguity, assume good intent
 - Use instances of inappropriate behavior to teach, not to shame
 - Absolutely forbid allowing or enabling offenses to live beyond correction & apology, in any public medium
 - Be an ideal for people to aspire to, not a stick to beat them with

This certainly doesn't mean there will be no explicit boundaries or repercussions, I just have yet to see a policy that strikes a balance between the one-dimensional and the ad-hoc. A friend pointed me to the [Open Code of Conduct](https://github.com/todogroup/opencodeofconduct), which I plan on poking through shortly. In the meantime, consider the foregoing to be the ground rules for the project going forward. Infractions can be reported to me directly. My email address is on my profile. I'll set up a `community@` account for the project at my earliest opportunity.

This informal policy has the full unanimous consensus of the project team. Thanks for your time, thoughtful consideration, and input. I'd love to have further input from the existing UI Router community and user base.

**Comment by warrenseymour** [comment]
@nateabele Beautifully stated.

**Comment by jessicard** [comment]
> I have to say I'm a bit taken aback by the fact that the people primarily championing this have, so far as I can tell, had no prior involvement in the project. I'm not entirely sure what to make of it, but I will proceed on the assumption that you're all here in good faith.

I don't think there's anything wrong with developers who like to contribute to open source suggesting to add a code of conduct so they feel they can contribute without harassment. However, since this seems to be controversial, i'm going to unsubscribe myself from this thread. Good luck.

**Comment by CoralineAda** [comment]
The Contributor Covenant is the default CoC for Ruby gems built with bundler and has been adopted by over 4700 projects. I strongly advise against trying to write your own CoC; documents like the CC have built on the collective, real-world experiences of marginalized people in tech.You ignore them at your own peril.

**Comment by nateabele** [comment]
> I don't think there's anything wrong with developers who like to contribute to open source suggesting to add a code of conduct so they feel they can contribute without harassment.

That's totally fair. I mentioned it because the events leading up to this discussion pattern-match to other incidents that I've seen go Downhill Fast™. To be clear, that is in no way a reflection on you.

> The Contributor Covenant is the default CoC for Ruby gems built with bundler and has been adopted by over 4700 projects.

Please don't take my comments as anything other than my assessment that the CC doesn't fit exactly with the culture I aspire to create for this project. This isn't a judgement of CC in the abstract, nor is it a suggestion that the CC isn't perfect for others.

> I strongly advise against trying to write your own CoC

I'm only slightly less interested in writing my own license (...that is, I am vehemently _disinterested_ in writing my own license). :smile: However, just as there are a variety of licenses to meet a variety of project needs and intents, it follows that there would be a variety of CoCs to address the many different styles and flavors of Open Source cultures and organizations. This is a topic I still don't know enough about and am interested in exploring. The above is a beginning, not an end.

> You ignore them at your own peril.

I'm curious as to what that peril might be.

**Comment by nateabele** [comment]
Adding another one for future reference: https://indiewebcamp.com/code-of-conduct

**Comment by petebacondarwin** [comment]
@nateabele I am very happy that you are taking this seriously and I am impressed that you are putting so much thought into the culture that you wish to cultivate in ui-router. I am sure that the team will agree on an acceptable code of conduct. Really the key is that people should know what to expect and how to act and that there is a clear path to dealing with indiscretions quickly and with the least amount of wasted time and upset for all those involved!

**Comment by kvz** [comment]
Not involved with the project (my intentions are good :relaxed:) but I stumbled upon this thread and just wanted to encourage and praise you for what you're doing here @nateabele

**Comment by nateabele** [comment]
@petebacondarwin Totally. The other part is, I haven't always treated people here the way *I* want to, so if I'm setting a standard of behavior that I know people will hold me accountable to in a constructive, encouraging way, that helps me, too.

@kvz Thanks buddy. :smile:

**Comment by wesleycho** [comment]
Just to add my thoughts - I agree wholeheartedly with the CoC. We implemented in our Angular 2 UI Bootstrap work, as can be seen [here](https://github.com/ng-bootstrap/core/blob/master/CODE_OF_CONDUCT.md) & should have it in UI Bootstrap soon as well, and personally believe it is only a good thing.

**Pull request closed without merging**
