### PR TITLE
Observe the ui-sref attribute so it can be updated if it changes.

### PR DESCRIPTION
**Pull request by rwlogel**
Currently if ui-sref changes after the directive is linked it is updated.  This change will observe the ui-sref and update the href if it changes.

### CODE REVIEW

**Comment by nateabele** [comment]
The state name in `ui-sref` is a literal, not an expression.

**Comment by rwlogel** [comment]
That isn't entirely true it is currently valid for the ui-sref to be:

```html
<select ng-model="foo">
    <!-- A selection box holding various entries that correspond to other states -->
</select>
<a  ui-sref="{{dynamicLinkToState()}}">Load Selected Entry</a>
```

This already works, but it will only reference the state provided at the time ui-sref is linked.  Adding the observe method will allow the user to dynamically change that entry.

**Comment by nateabele** [comment]
That's incidental to the way Angular works, and is irrespective of `uiSref`'s design. There's an alternative proposal to support dynamic watching (and the attendant performance cost) in a separate directive.

**Comment by plong0** [comment]
+1 for observing ui-sref attribute

@nateabele can I ask what is the alternative proposal around this?

**Comment by nateabele** [comment]
@plong0 We just merged a `ui-state` directive to master. It'll be out in the next release.

**Comment by plong0** [comment]
cool!  looking forward to the release.  would you say the master branch and ui-state on it are stable enough for production?  or better to wait for the official release?

**Comment by nateabele** [comment]
All the tests are passing, so it's as stable as any other release. :smile:

**Pull request closed without merging**
