### PR TITLE
fix(urlMatcherFactory.js): Url will not be matched if param value is not of param type and it is not optional

### PR DESCRIPTION
**Pull request by kruczy**
Hi,
 this is a simple patch to not match url if the parameter value is invalid and not optional I think it is necessary as not all custom types can have a regex that represents all valid values and if they don't router does not resolve subsequent routes properly

### CODE REVIEW

**Comment by kruczy** [comment]
Any chance of getting this merged? or is there a better way to fix it? anyone?

**Comment by nateabele** [comment]
I think this makes sense. @christopherthielen?

Also: http://prjs.radify.io/#/angular-ui/ui-router/pulls/2086

**Comment by christopherthielen** [comment]
What if the parameter IS optional, but it doesn't match the `.is()` test?

**Comment by kruczy** [comment]
If it is optional does it have to pass the test? Could remove the isOptional bit if it does

**Pull request closed without merging**
