### PR TITLE
docs(Ng1StateHooks): Corrected interface and docs

### LINKED ISSUE #3072: State.onEnter() does not behave as documented
Hello,

The `onEnter` hook on the state declaration does not match the documentation:
https://ui-router.github.io/docs/latest/interfaces/ng1.ng1statedeclaration.html#onenter

``` javascript
.state({
  name: 'mystate',
  onEnter: function(trans, state) {
    console.log("Entering " + state.name);
  }
});
```

When I use `onEnter` it is injected by angular DI as usual (Angular 1.5). See plunkr for details:
https://plnkr.co/edit/lNS6CJThVvd1MK1y2AFd?p=preview

I can't create a pull request, since I'm not sure which is the correct option.

Have I missed something or is this not working as intended?

### PR DESCRIPTION
**Pull request by csvn**
Updated interfaces and documentation to fix #3072

Not sure if documentation looks correct, since I wasn't able to build it correctly.

### CODE REVIEW

**Comment by csvn** [comment]
With this change, at least typings/Typescript won't throw errors with dependency injection in Angular 1.

**Comment by christopherthielen** [comment]
Did you mean to close this?

**Comment by csvn** [comment]
No, I messed up with my master branch and it closed automatically. I could not open it :)

I was looking into the travis build failures. I found out why it's messed up. But maybe this is not the right place to discuss it, or you might already know how to fix it.

**Comment by csvn** [comment]
The [failed check in travis](https://travis-ci.org/angular-ui/ui-router/jobs/169589349#L183-L195) can be solved by upgrading npm above v3 ([found it here](https://github.com/AngularClass/angular2-webpack-starter/issues/501#issuecomment-207489701)). I tried this on my fork, and it made that particular error go away.

The next error that pops up is due to the cloning and installing of [ui-router/core from travis](https://github.com/angular-ui/ui-router/blob/master/.travis.yml#L30). When `npm install ./ui-router-core` is run, it will trigger the `prepublish` hook in `ui-router/core` ([which will be deprecated in npm@4](https://github.com/npm/npm/releases/tag/v4.0.0)). This would be fine, except that the `npm test` script fails miserably due to no `node_modules` being installed.

So a possible solution would be to `cd ui-router-core && npm i && cd ..` to install node_modules in the cloned core repo, but that would add alot of time to the build. Since I could not find an easy solution to the failing Travis build, I'll just add my findings here for now.

**Pull request merged**
